FROM ubuntu:latest

# Set the MySQL root password using an environment variable
ENV MYSQL_ROOT_PASSWORD=mysecretpassword
RUN groupadd -r mysql && useradd -r -g mysql mysql

# pre-installs
RUN apt-get update
RUN apt-get install -y \
    mysql-server \
    mysql-client 

# Create a new database and a user with privileges for that database
RUN service mysql start && \
    mysql -u root -p ${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE mydatabase;" && \
    mysql -u root -p ${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser'@'%' IDENTIFIED BY 'mypassword';"

