# to reference a local build of the kg2 image
ARG IMAGE_REF=localhost:5000/kg2
# hadolint ignore=DL3007
FROM ${IMAGE_REF}:latest

# add additional apt dependencies
# hadolint ignore=DL3008
RUN apt-get install -y screen --no-install-recommends

# copy the contents of this repo to the container
COPY . /home/ubuntu/RTX-KG2

# make this container persistent
CMD ["tail -f /dev/null"]
